### ISSUE TITLE
Xmx option doesn't limit memory usage

### ISSUE THREAD

**Issue by Na3blis** [blacklabelops/jira#20]
I'm trying to limit the memory usage of jira. My compose file looks like:
```
jira:
    image: blacklabelops/jira
    container_name: jira
    mem_limit: 1350m
    volumes:
      - jira_home:/var/atlassian/jira
    ports:
      - 8080:8080
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx400m'
    network_mode: "host"
    depends_on:
      - "postgres"
    restart: always
```
I set Xmx to 400 just to test the memory usage. Just from starting the container, I get up to 1gb. Shouldn't the Xmx400m limit that, or am I misunderstanding the purpose of that? If so, is there any other way to limit the memory usage? The problem I'm running into is when jira uses too much memory, the container just restarts. 

Also, it appears your hipchat is down. I just get redirected to hipchat signup
