### ISSUE TITLE
Loaded with failures over JIRA running behind HAProxy

### ISSUE THREAD

**Issue by ain** [blacklabelops/jira#47]
As in reference to #10, I'm still having loads of failures on JIRA that is running behind HAProxy that sets SSL cert. Sometimes pages just go _Safari can't open the page_ because the server where page is located is not responding.

`docker-compose.yml`:

```yaml
version: '2'
services:
  web:
    image: 'blacklabelops/jira:7.5.0'
    hostname: 'jira.mydomain.com'
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
    volumes:
      - ./jira:/var/atlassian/jira
    environment:
      JIRA_DATABASE_URL: 'mysql://jira@db/jira'
      JIRA_DB_PASSWORD: 'mypass'
      JIRA_PROXY_NAME: 'jira.mydomain.com'
      JIRA_PROXY_PORT: '443'
      JIRA_PROXY_SCHEME: 'https'
      DOCKER_WAIT_HOST: 'db'
      DOCKER_WAIT_PORT: '3306'
    logging:
      driver: json-file
      options:
        max-size: 10m
  db:
    image: mariadb:10.1
    environment:
      MYSQL_DATABASE: 'jira'
      MYSQL_USER: 'jira'
      MYSQL_PASSWORD: 'mypass'
      MYSQL_ROOT_PASSWORD: 'myrootpass'
    volumes:
      - ./data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
```

`haproxy.cfg`:

```config
frontend https-in                   
  bind *:443 ssl crt /etc/haproxy/certs/
  reqadd X-Forwarded-Proto:\ https  
  mode http                         

  acl jira_control hdr(host) -i jira.mydomain.com
  use_backend jira_backend if jira_control 

backend jira_backend
  redirect scheme https if !{ ssl_fc }
  balance leastconn                 
  option httpclose
  option forwardfor
  server jira 127.0.0.1:8080
```
