### ISSUE TITLE
Check if Postgres Database is ready before startup

### ISSUE THREAD

**Issue by dustycodes** [blacklabelops/jira#80]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description

Jira starts up before postgres is ready most of the time. It would be nice to have an option where the jira container checks if postgres is ready like (this)[https://github.com/docker/compose/issues/374#issuecomment-300671114]

### Steps to Reproduce

1. docker-compose file with postgres database and jira containers
2. docker-compose up
3. jira is broken with generic "cannot connect to database" page

**Expected behavior:** Jira container to check for dependent database to be ready

**Actual behavior:** A race condition on startup with the database

**Reproduces how often:** For me, every time. But I imagine this changes depending on a lot of factors.

### Versions
blacklabelops/jira:7.6.0

### Logs And Environment Information
Docker version 1.13.1, build 092cba3
Ubuntu Release:        16.04
docker-compose version 1.8.0

``` yml
version: '2.0'
services:

  jira-postgres:
    build: jira-postgres
    restart: always
    networks:
      - atlassian
    volumes:
      - /etc/timezone:/etc/timezone
      - jiraDatabaseVol:/var/lib/postgresql/data

  jira:
    build: jira
    restart: always
    networks:
      atlassian:
        aliases:
          - jira
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone
      - jiraVol:/var/atlassian/jira
    links:
      - jira-postgres:postgres
    environment:
      - "JIRA_DATABASE_URL=postgresql://jirauser@postgres/jiradbihave"
      - "JIRA_DB_PASSWORD=mypassword"
      - "JIRA_PROXY_NAME=jira.proxy.net"
      - "JIRA_PROXY_PORT=443"
      - "JIRA_PROXY_SCHEME=https"
    depends_on:
      - jira-postgres
```
