### ISSUE TITLE
Limit Docker logging?

### ISSUE THREAD

**Issue by jhult** [blacklabelops/jira#92]
Should [Docker logging](https://github.com/docker/compose/issues/1083) be limited by adding something as follows to [docker-compose.yml](/blacklabelops/jira/blob/master/docker-compose.yml)?

```
logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
```
